### ISSUE TITLE
[Request] Front camera capture

### ISSUE THREAD

**Issue by GyuhoEoh** [lge-ros2/multi-robot-simulator#7]
**Is your feature request related to a problem? Please describe.**
I cannot get images from this simulator.

**Describe the solution you'd like**
I want to get images from the multi-robot-simulator. These images should be acquired from the cameras of (virtual) robots. Additionally, each image should synchronize with the robot's position.

**Describe alternatives you've considered**
Image capturing should be possible at any time. I want to adjust a frame rate and image resolution too.

**Additional context**

**Comment by hyunseok-yang** [comment]
I will initiate those sensor model!

**Comment by hyunseok-yang** [comment]
@GyuhoEoh  Are you considering only single camera or multi-camera?

**Comment by GyuhoEoh** [comment]
> @GyuhoEoh Are you considering only single camera or multi-camera?
I want to attach multiple cameras to a robot.

**Comment by hyunseok-yang** [comment]
> > @GyuhoEoh Are you considering only single camera or multi-camera?
> > I want to attach multiple cameras to a robot.
How many cameras do you want to attach on the robot? Too many cameras can cause the low performance issue.

**Comment by GyuhoEoh** [comment]
I expect that five cameras are necessary. (front, back, left, right, ceiling view)

**Comment by hyunseok-yang** [comment]
> I expect that five cameras are necessary. (front, back, left, right, ceiling view)

Ok, I will investigate it first.

**Comment by hyunseok-yang** [comment]
@GyuhoEoh  

Hi!

I've had an investigation about synchronizing multiple images from camera.

I think the role of simulator is only publishing images similar to real sensor.

And you'd better to use below ROS2 packages to synchronize multiple images.
(I also not fully understand the usage of these packages but, as far as I know these packages will help what you want!)

http://wiki.ros.org/image_pipeline
http://wiki.ros.org/image_proc
http://wiki.ros.org/stereo_image_proc
https://github.com/ros-perception/image_pipeline/tree/ros2


**OR** there is timestamp information in the header field of sensor_msgs::Image. So.. .you could utilize that timestamp I guess..

https://github.com/ros2/common_interfaces/blob/dashing/sensor_msgs/msg/Image.msg

**Comment by hyunseok-yang** [comment]
Camera(+multi-camera) sensor model is done now!

Currently, intrinsic parameter for camera is not supported and camera performance could be not enough as you expected like latency(update rate).

The performance depends on parameters on sensor(camera) element in robot description(SDF).

Please check latest commit on sim-device repository to publish sensor data through ROS2 topic.

![image](https://user-images.githubusercontent.com/21001946/82657924-1e293800-9c61-11ea-962f-604dddbaed5f.png)
